### ISSUE TITLE
Undefined method `uri' when generating image

### ISSUE THREAD

**Issue by yingliangzhang** [dfry22/shopify-sample-data#2]
Hi,

Firstly I want to thank you for this.

I got an error when I run the script, it's coming from the function

```
def gen_image_src
    # we can choose specific criteria but I choose first to make it easy
    return Google::Search::Image.new(query: @title).first.uri
  end
```

product.rb:99:in `gen_image_src': undefined method`uri' for nil:NilClass (NoMethodError)

Looks like it could not find a image?

**Comment by davefreiman** [comment]
Hey there, getting the same error, looks like Google-Search Gem was updated - will let you know when this is fixed - meantime you can checkout rev `934f2e0` which doesn't depend on that gem and try that

**Comment by davefreiman** [comment]
going to remove the dependency on google search this week, sorry for the delay

**Comment by yingliangzhang** [comment]
@dfry22 Yeah no problem. Thanks for the reply :)

**Comment by davefreiman** [comment]
@yingliangzhang Sorry for the delay. Just pushed a fix here
